#!/bin/bash

if [ ! -n "$1" ]; then
	echo "Please input an exercise id";
	exit;
fi

exercise_id="$1";

temp_file=$(mktemp)
echo "Temporary file $temp_file created"
minimum_date=$(sqlite3 data/db 'SELECT MIN(date) FROM session;');
name=$(sqlite3 data/db "SELECT name FROM exercise WHERE id = ${exercise_id};");
sqlite3 data/db "SELECT ROUND(JULIANDAY(session.date) - JULIANDAY('$minimum_date')),completed_exercise.weight FROM completed_exercise LEFT JOIN session ON session.id = completed_exercise.session_id WHERE completed_exercise.exercise_id = ${exercise_id};" | sed -e 's/|/ /' > $temp_file
cat exercise_weight.gnuplot | sed -e "s#<myfile>#$temp_file#" -e "s#<min-date>#${minimum_date}#" | gnuplot - > /dev/null
rm $temp_file
